[WIP] Feat/connect sign in status changed middleware
Greenruhm/connect pull request #83
Opened 2023-06-03 00:06 UTC by brunomoutinho

2023-06-08 18:26 UTC, Frenziecodes approved these changes

2023-07-04 19:21 UTC, ericelliott commented
What's the status of this? It is out of sync with the base branch.

2023-07-10 19:00 UTC, ericelliott requested changes
See comments.

2023-07-10 19:00 UTC, ericelliott commented on docs/components/index.md
> +And, finally, you might want to create your own components and deal with calling the Greenruhm Connect SDK methods yourself. In that case, just configure the SDK as showed above and use `useConnect`.
If you implement my suggested change above, you can delete this paragraph.

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +| ErrorComponent   | component     | N/A           | A component to display in case of an error. This prop will not be used in case `ViewComponent` is passed as well. |
In all of these override cases, say:

If `ViewComponent` is passed, this component is ignored because the `ViewComponent` should handle this.

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +| FormComponent    | component     | N/A           | A component that renders the sign-up form. This prop will not be used in case `ViewComponent` is passed as well. |
This should be sign-in. This copy-pasta is also in these other descriptions:

* [ ] LoadingComponent
* [ ] ViewComponent
* [ ] SuccessComponent

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +| onSuccess        | function      | console.log() | A function that will be called upon successful sign-in. The default function logs the user data to the console. The `onSuccess` signature is as fo
I would link this to `onSuccess` function documentation below this table rather than trying to document `onSuccess` inline here.

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +import ReactDOM from 'react-dom';
Is this used?

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +import ReactDOM from 'react-dom';
ReactDOM?

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +  // You should use `AuthStatuses` to determine what your component should display.
Please document `AuthStatuses`

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +`FormComponent` overrides the default, Greenruhm provided form. By providing this prop, the client must take care of the interaction of the user with the form as well as rendering the errors (either
default, <-- omit comma

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-in.md
> +  // and navigating somewhere else in your application, for examplle.
examplle/example

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-up.md
Implement the suggested changes from sign-in

2023-07-10 19:00 UTC, ericelliott commented on docs/components/sign-up.md
> +  // and navigating somewhere else in your application, for examplle.
examplle/example

2023-07-17 18:09 UTC, ericelliott commented on docs/components/index.md
> +const withProviders = (Component) =>
You don't need to explicitly provide Component and pass it in here. Please simplify.

2023-07-17 18:14 UTC, ericelliott commented on docs/components/sign-up.md
> +import ReactDOM from 'react-dom';
here

2023-07-17 18:34 UTC, ericelliott approved these changes
LGTM

2023-07-18 20:33 UTC, merged